# Generated by Django 2.0.5 on 2018-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='title',
            field=models.CharField(default='useless title', max_length=20),
        ),
    ]
