# Generated by Django 2.0.5 on 2018-08-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0002_style_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='model_name',
            new_name='model',
        ),
    ]
