# Generated by Django 2.0.5 on 2018-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0003_auto_20180804_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='author',
        ),
        migrations.AlterField(
            model_name='style',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
