# Generated by Django 2.0.5 on 2018-08-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0004_auto_20180804_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
