# Generated by Django 2.0.5 on 2018-08-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0006_auto_20180804_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='source_file',
            field=models.ImageField(default='', upload_to='source_files'),
        ),
    ]
