# Generated by Django 2.0.5 on 2018-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_manager', '0007_auto_20180805_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='style_model_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
